// Copyright 2024-2025 Irreducible Inc.
// Copyright 2026 The Binius Developers

use std::{iter, ops::Deref};

use binius_field::{ExtensionField, Field, FieldOps, PackedField, WideMul};
use binius_utils::rayon::{
	prelude::*,
	task_size::{IndexedParallelIteratorExt, WorkPerItem},
};

use crate::FieldBuffer;

#[inline]
pub fn inner_product<F: Field>(
	a: impl IntoIterator<Item = F>,
	b: impl IntoIterator<Item = F>,
) -> F {
	inner_product_subfield(a, b)
}

#[inline]
pub fn inner_product_scalars<F: FieldOps>(
	a: impl IntoIterator<Item = F>,
	b: impl IntoIterator<Item = F>,
) -> F {
	itertools::zip_eq(a, b).map(|(a_i, b_i)| b_i * a_i).sum()
}

#[inline]
pub fn inner_product_subfield<F, FSub>(
	a: impl IntoIterator<Item = FSub>,
	b: impl IntoIterator<Item = F>,
) -> F
where
	F: Field + ExtensionField<FSub>,
	FSub: Field,
{
	itertools::zip_eq(a, b).map(|(a_i, b_i)| b_i * a_i).sum()
}

#[inline]
pub fn inner_product_par<F, P, DataA, DataB>(
	a: &FieldBuffer<P, DataA>,
	b: &FieldBuffer<P, DataB>,
) -> F
where
	F: Field,
	P: PackedField<Scalar = F>,
	DataA: Deref<Target = [P]>,
	DataB: Deref<Target = [P]>,
{
	let n = a.len();
	// Accumulate the products in unreduced (wide) form and reduce a single time at the end. For
	// packed `GF(2^128)` fields this amortizes the reduction cost across all products; for every
	// other field the widening multiply is the trivial (eager) one, so this is identical to a plain
	// product-then-sum.
	let wide_sum = a
		.as_ref()
		.par_iter()
		.zip_eq(b.as_ref().par_iter())
		.with_min_task(WorkPerItem::FieldMuls)
		.map(|(&a_i, &b_i)| P::wide_mul(a_i, b_i))
		.sum::<<P as WideMul>::Output>();
	P::reduce(wide_sum).into_iter().take(n).sum()
}

#[inline]
pub fn inner_product_buffers<F, P, DataA, DataB>(
	a: &FieldBuffer<P, DataA>,
	b: &FieldBuffer<P, DataB>,
) -> F
where
	F: Field,
	P: PackedField<Scalar = F>,
	DataA: Deref<Target = [P]>,
	DataB: Deref<Target = [P]>,
{
	let log_n = a.log_len();
	inner_product_packed(log_n, a.as_ref().iter().copied(), b.as_ref().iter().copied())
}

/// Compute the inner product of two scalar sequences generated by iterators of packed elements.
///
/// ## Preconditions
///
/// * `a` and `b` have length `1 << log_n.saturating_sub(P::LOG_WIDTH)`
#[inline]
pub fn inner_product_packed<F, P>(
	log_n: usize,
	a: impl ExactSizeIterator<Item = P>,
	b: impl ExactSizeIterator<Item = P>,
) -> F
where
	F: Field,
	P: PackedField<Scalar = F>,
{
	assert_eq!(a.len(), 1 << log_n.saturating_sub(P::LOG_WIDTH)); // pre-condition
	assert_eq!(b.len(), 1 << log_n.saturating_sub(P::LOG_WIDTH)); // pre-condition

	// See `inner_product_par` for why the products are accumulated in unreduced (wide) form.
	let wide_sum = iter::zip(a, b)
		.map(|(a_i, b_i)| P::wide_mul(a_i, b_i))
		.sum::<<P as WideMul>::Output>();
	P::reduce(wide_sum).into_iter().take(1 << log_n).sum()
}

#[cfg(test)]
mod tests {
	use binius_field::{PackedBinaryGhash4x128b, Random};
	use rand::{SeedableRng, rngs::StdRng};

	use super::*;

	// The packed inner products defer the `GF(2^128)` reduction (widening multiply). Check the
	// reduced result against a naive scalar-by-scalar reference.
	#[test]
	fn test_inner_product_matches_naive() {
		use binius_field::BinaryField128bGhash;

		type P = PackedBinaryGhash4x128b;
		type F = BinaryField128bGhash;

		let mut rng = StdRng::seed_from_u64(42);

		for log_n in [4, 8, 12] {
			let n = 1 << log_n;
			let a_vals: Vec<P> = (0..n / P::WIDTH).map(|_| P::random(&mut rng)).collect();
			let b_vals: Vec<P> = (0..n / P::WIDTH).map(|_| P::random(&mut rng)).collect();

			let buffer_a = FieldBuffer::new(log_n, a_vals);
			let buffer_b = FieldBuffer::new(log_n, b_vals);

			let naive: F = (0..n).map(|i| buffer_a.get(i) * buffer_b.get(i)).sum();

			let par: F = inner_product_par(&buffer_a, &buffer_b);
			let buffers: F = inner_product_buffers(&buffer_a, &buffer_b);
			assert_eq!(par, naive, "inner_product_par mismatch at log_n={log_n}");
			assert_eq!(buffers, naive, "inner_product_buffers mismatch at log_n={log_n}");
		}
	}

	#[test]
	fn test_inner_product_packing_width_greater_than_buffer_length() {
		type P = PackedBinaryGhash4x128b;

		let mut rng = StdRng::seed_from_u64(0);

		// Create buffers with log_len = 0 (1 element), but packing width = 4
		let packed_a = P::random(&mut rng);
		let packed_b = P::random(&mut rng);

		let buffer_a = FieldBuffer::new(0, vec![packed_a]);
		let buffer_b = FieldBuffer::new(0, vec![packed_b]);

		// Compute inner product using both functions
		let result_par = inner_product_par(&buffer_a, &buffer_b);
		let result_packed = inner_product_buffers(&buffer_a, &buffer_b);

		// Compute expected result manually - only first element should be used
		let expected = buffer_a.get(0) * buffer_b.get(0);

		assert_eq!(result_par, expected, "inner_product_par failed for log_len=0");
		assert_eq!(result_packed, expected, "inner_product_packed failed for log_len=0");
	}
}
